### ISSUE TITLE
[Feature Request] iter8ctl logs function

### ISSUE THREAD

**Issue by kalantar** [iter8-tools/iter8ctl#27]
**Is your feature request related to a problem? Please describe.**
When problems occur, it is useful to see what happened in the handler. In particular, if the user writes their own actions they will want to add "print" statements to help them develop the function they have in mind. We should enable them to se the results. 

**Why is the feature useful for Iter8 users?**
Provide means to enable users to write and debug actions. I found the ability to look at the logs of the handlers essential.

**Describe the solution you'd like**
Enable `iter8ctl logs <action>`, for example, `iter8ctl logs start` to see the logs of the start actions.
To enable this we will need: 

- [ ] label on handler job/pod that identifies the action label. Currently, this is in the name only.
- [ ] try jobs only once. There doesn't seem to be any reason to try multiple times in the case of failure

**Describe alternatives you've considered**
None

**Does this issue require a design doc/discussion? If there is a link to the design document/discussions, please provide it below.**
Probably needs review

**How will this feature be tested?**
TBD

**How will this feature be documented?**
Document in project README.md.

**Comment by sriumcp** [comment]
When an experiment launches a start job, is there a specific (deterministic) name for the start job?

**Comment by sriumcp** [comment]
Wouldn't `kubectl logs -n iter8-system job/<experiment-name>-start` work?

**Comment by kalantar** [comment]
The names have a random string in them to handle loop handlers. It would be an alternative as well but means other changes.

You are right that my suggestion is insufficient in that it does not identify the experiment. Something like your suggestion makes sense. Further design must be done.
